// Traductions du parcours public (interface + documents générés).
// Les directives envoyées au modèle restent en français ; le texte produit suit
// la langue choisie par le visiteur.

export const LANGUAGES = Object.freeze([
  { code: "fr", label: "Français", flag: "🇫🇷", englishName: "French" },
  { code: "en", label: "English", flag: "🇬🇧", englishName: "English" },
  { code: "de", label: "Deutsch", flag: "🇩🇪", englishName: "German" },
  { code: "es", label: "Español", flag: "🇪🇸", englishName: "Spanish" },
  { code: "it", label: "Italiano", flag: "🇮🇹", englishName: "Italian" }
]);

export function isSupportedLanguage(code) {
  return LANGUAGES.some((entry) => entry.code === code);
}

export function normalizeLanguage(code) {
  const value = String(code ?? "").slice(0, 2).toLowerCase();
  return isSupportedLanguage(value) ? value : "fr";
}

export function englishNameFor(code) {
  return LANGUAGES.find((entry) => entry.code === normalizeLanguage(code))?.englishName ?? "French";
}

const FR = {
  brand: "Lastro · Lecture symbolique personnalisée",
  person: "Personne",
  generatedOn: "Généré le",
  caveat:
    "Cadre : cette lecture est une cartographie intérieure, symbolique et non prédictive. Elle ne constitue ni un diagnostic, ni une thérapie, ni une prédiction d'événements. Le libre arbitre reste entier. Les données astronomiques utilisées sont vérifiées (annexe technique) ; les interprétations restent des lectures symboliques.",
  writerNoteLlm: "Rédaction : rédacteur IA configuré, sections validées par la machine avant relecture humaine.",
  writerNoteTemplate: "Brouillon : rédacteur IA non configuré (clé absente). Ce document n'est pas prêt pour la livraison.",
  footer:
    "Document généré par Lastro — socle de calcul local et déterministe ; toute interprétation est étiquetée et doit être relue avant livraison.",
  badgeCalculated: "Données vérifiées (calcul)",
  badgeSymbolic: "Lecture symbolique",
  badgeUnavailable: "Module non disponible dans cette version",
  statusOk: "validé machine",
  statusNeedsReview: "à vérifier",
  statusNotAvailable: "non disponible",
  statusTemplateDraft: "brouillon (sans rédacteur IA)",
  statusLabelPrefix: "Statut",
  annexTitle: "Annexe — socle de calcul vérifié",
  annexIntro:
    "Cette annexe contient les seules données calculées et vérifiées utilisées pour ce dossier. Aucune interprétation n'y figure.",
  uncertaintyLimits: "Limites d'incertitude",
  engineWarnings: "Avertissements du moteur de calcul",
  unavailableText:
    "Aucune prédiction d'événement n'est produite : ce module livrera des fenêtres larges, des thèmes de maturation et des postures intérieures (0–1 an, 1–3 ans, 3–5 ans).",
  titlePrefix: "Lecture symbolique",
  sectionTitles: {
    introduction: "Introduction — cadre de la lecture",
    "position-naissance-axe": "Position de naissance & axe de vie",
    "structure-psychologique": "Structure psychologique & émotionnelle",
    transgenerationnel: "Lecture transgénérationnelle",
    "archetypes-dominants": "Archétypes dominants",
    "lecture-passe": "Lecture approfondie du passé",
    "lettre-ame": "Lettre d'âme",
    "lettre-miroir": "Lettre miroir",
    "periodes-cycles": "Périodes & Cycles",
    "cles-integration": "Clés d'intégration",
    "conclusion-ethique": "Conclusion éthique"
  }
};

const EN = {
  brand: "Lastro · Personalised symbolic reading",
  person: "Person",
  generatedOn: "Generated on",
  caveat:
    "Scope: this reading is an inner, symbolic and non-predictive map. It is neither a diagnosis, nor therapy, nor a prediction of events. Free will remains fully yours. The astronomical data used is verified (technical annex); the interpretations remain symbolic readings.",
  writerNoteLlm: "Writing: AI writer configured, sections machine-validated before human review.",
  writerNoteTemplate: "Draft: AI writer not configured (no key). This document is not ready for delivery.",
  footer:
    "Document generated by Lastro — local and deterministic calculation base; every interpretation is labelled and must be reviewed before delivery.",
  badgeCalculated: "Verified data (calculation)",
  badgeSymbolic: "Symbolic reading",
  badgeUnavailable: "Module not available in this version",
  statusOk: "machine-validated",
  statusNeedsReview: "to review",
  statusNotAvailable: "not available",
  statusTemplateDraft: "draft (no AI writer)",
  statusLabelPrefix: "Status",
  annexTitle: "Technical annex — verified calculation base",
  annexIntro: "This annex contains the only calculated and verified data used for this reading. No interpretation appears here.",
  uncertaintyLimits: "Uncertainty limits",
  engineWarnings: "Calculation engine warnings",
  unavailableText:
    "No event prediction is produced: this module will provide broad windows, maturation themes and inner postures (0–1 year, 1–3 years, 3–5 years).",
  titlePrefix: "Symbolic reading",
  sectionTitles: {
    introduction: "Introduction — the frame of the reading",
    "position-naissance-axe": "Birth position & life axis",
    "structure-psychologique": "Psychological & emotional structure",
    transgenerationnel: "Transgenerational reading",
    "archetypes-dominants": "Dominant archetypes",
    "lecture-passe": "In-depth reading of the past",
    "lettre-ame": "Soul letter",
    "lettre-miroir": "Mirror letter",
    "periodes-cycles": "Periods & Cycles",
    "cles-integration": "Keys to integration",
    "conclusion-ethique": "Ethical conclusion"
  }
};

const DE = {
  brand: "Lastro · Persönliche symbolische Deutung",
  person: "Person",
  generatedOn: "Erstellt am",
  caveat:
    "Rahmen: Diese Deutung ist eine innere, symbolische und nicht vorhersagende Landkarte. Sie ist weder eine Diagnose noch eine Therapie noch eine Vorhersage von Ereignissen. Dein freier Wille bleibt vollständig erhalten. Die verwendeten astronomischen Daten sind geprüft (technischer Anhang); die Deutungen bleiben symbolisch.",
  writerNoteLlm: "Text: KI-Autor konfiguriert, Abschnitte vor der menschlichen Prüfung maschinell validiert.",
  writerNoteTemplate: "Entwurf: Kein KI-Autor konfiguriert (kein Schlüssel). Dieses Dokument ist nicht lieferbereit.",
  footer:
    "Von Lastro erstelltes Dokument — lokale und deterministische Berechnungsgrundlage; jede Deutung ist gekennzeichnet und vor der Auslieferung zu prüfen.",
  badgeCalculated: "Geprüfte Daten (Berechnung)",
  badgeSymbolic: "Symbolische Deutung",
  badgeUnavailable: "Modul in dieser Version nicht verfügbar",
  statusOk: "maschinell validiert",
  statusNeedsReview: "zu prüfen",
  statusNotAvailable: "nicht verfügbar",
  statusTemplateDraft: "Entwurf (ohne KI-Autor)",
  statusLabelPrefix: "Status",
  annexTitle: "Technischer Anhang — geprüfte Berechnungsgrundlage",
  annexIntro: "Dieser Anhang enthält nur die berechneten und geprüften Daten dieser Deutung. Es steht keine Interpretation darin.",
  uncertaintyLimits: "Unsicherheitsgrenzen",
  engineWarnings: "Hinweise der Berechnungs-Engine",
  unavailableText:
    "Es werden keine Ereignisse vorhergesagt: Dieses Modul liefert breite Zeitfenster, Reifethemen und innere Haltungen (0–1 Jahr, 1–3 Jahre, 3–5 Jahre).",
  titlePrefix: "Symbolische Deutung",
  sectionTitles: {
    introduction: "Einführung — Rahmen der Deutung",
    "position-naissance-axe": "Geburtsstellung & Lebensachse",
    "structure-psychologique": "Psychische & emotionale Struktur",
    transgenerationnel: "Transgenerationale Deutung",
    "archetypes-dominants": "Dominante Archetypen",
    "lecture-passe": "Vertiefte Deutung der Vergangenheit",
    "lettre-ame": "Seelenbrief",
    "lettre-miroir": "Spiegelbrief",
    "periodes-cycles": "Phasen & Zyklen",
    "cles-integration": "Schlüssel zur Integration",
    "conclusion-ethique": "Ethischer Abschluss"
  }
};

const ES = {
  brand: "Lastro · Lectura simbólica personalizada",
  person: "Persona",
  generatedOn: "Generado el",
  caveat:
    "Marco: esta lectura es un mapa interior, simbólico y no predictivo. No constituye un diagnóstico, ni una terapia, ni una predicción de acontecimientos. El libre albedrío permanece intacto. Los datos astronómicos utilizados están verificados (anexo técnico); las interpretaciones siguen siendo lecturas simbólicas.",
  writerNoteLlm: "Redacción: redactor IA configurado, secciones validadas por la máquina antes de la revisión humana.",
  writerNoteTemplate: "Borrador: redactor IA no configurado (sin clave). Este documento no está listo para entregar.",
  footer:
    "Documento generado por Lastro — base de cálculo local y determinista; toda interpretación está etiquetada y debe revisarse antes de la entrega.",
  badgeCalculated: "Datos verificados (cálculo)",
  badgeSymbolic: "Lectura simbólica",
  badgeUnavailable: "Módulo no disponible en esta versión",
  statusOk: "validado por máquina",
  statusNeedsReview: "por revisar",
  statusNotAvailable: "no disponible",
  statusTemplateDraft: "borrador (sin redactor IA)",
  statusLabelPrefix: "Estado",
  annexTitle: "Anexo técnico — base de cálculo verificada",
  annexIntro: "Este anexo contiene únicamente los datos calculados y verificados de esta lectura. No figura ninguna interpretación.",
  uncertaintyLimits: "Límites de incertidumbre",
  engineWarnings: "Avisos del motor de cálculo",
  unavailableText:
    "No se predice ningún acontecimiento: este módulo ofrecerá ventanas amplias, temas de maduración y posturas interiores (0–1 año, 1–3 años, 3–5 años).",
  titlePrefix: "Lectura simbólica",
  sectionTitles: {
    introduction: "Introducción — el marco de la lectura",
    "position-naissance-axe": "Posición de nacimiento y eje de vida",
    "structure-psychologique": "Estructura psicológica y emocional",
    transgenerationnel: "Lectura transgeneracional",
    "archetypes-dominants": "Arquetipos dominantes",
    "lecture-passe": "Lectura profunda del pasado",
    "lettre-ame": "Carta del alma",
    "lettre-miroir": "Carta espejo",
    "periodes-cycles": "Períodos y ciclos",
    "cles-integration": "Claves de integración",
    "conclusion-ethique": "Conclusión ética"
  }
};

const IT = {
  brand: "Lastro · Lettura simbolica personalizzata",
  person: "Persona",
  generatedOn: "Generato il",
  caveat:
    "Quadro: questa lettura è una mappa interiore, simbolica e non predittiva. Non è una diagnosi, né una terapia, né una previsione di eventi. Il libero arbitrio resta intero. I dati astronomici utilizzati sono verificati (appendice tecnica); le interpretazioni restano letture simboliche.",
  writerNoteLlm: "Scrittura: autore IA configurato, sezioni validate dalla macchina prima della revisione umana.",
  writerNoteTemplate: "Bozza: autore IA non configurato (chiave assente). Questo documento non è pronto per la consegna.",
  footer:
    "Documento generato da Lastro — base di calcolo locale e deterministica; ogni interpretazione è etichettata e va rivista prima della consegna.",
  badgeCalculated: "Dati verificati (calcolo)",
  badgeSymbolic: "Lettura simbolica",
  badgeUnavailable: "Modulo non disponibile in questa versione",
  statusOk: "validato dalla macchina",
  statusNeedsReview: "da rivedere",
  statusNotAvailable: "non disponibile",
  statusTemplateDraft: "bozza (senza autore IA)",
  statusLabelPrefix: "Stato",
  annexTitle: "Appendice tecnica — base di calcolo verificata",
  annexIntro: "Questa appendice contiene solo i dati calcolati e verificati di questa lettura. Non contiene alcuna interpretazione.",
  uncertaintyLimits: "Limiti di incertezza",
  engineWarnings: "Avvisi del motore di calcolo",
  unavailableText:
    "Non viene prodotta alcuna previsione di eventi: questo modulo offrirà finestre ampie, temi di maturazione e posture interiori (0–1 anno, 1–3 anni, 3–5 anni).",
  titlePrefix: "Lettura simbolica",
  sectionTitles: {
    introduction: "Introduzione — il quadro della lettura",
    "position-naissance-axe": "Posizione di nascita e asse di vita",
    "structure-psychologique": "Struttura psicologica ed emotiva",
    transgenerationnel: "Lettura transgenerazionale",
    "archetypes-dominants": "Archetipi dominanti",
    "lecture-passe": "Lettura approfondita del passato",
    "lettre-ame": "Lettera dell'anima",
    "lettre-miroir": "Lettera specchio",
    "periodes-cycles": "Periodi e cicli",
    "cles-integration": "Chiavi di integrazione",
    "conclusion-ethique": "Conclusione etica"
  }
};

const DOCS = { fr: FR, en: EN, de: DE, es: ES, it: IT };

export function docStrings(code) {
  const language = normalizeLanguage(code);
  const table = DOCS[language] ?? FR;
  const details = DETAILS[language] ?? DETAILS.fr;
  return {
    ...FR,
    ...table,
    ...details,
    sectionTitles: { ...FR.sectionTitles, ...(table.sectionTitles ?? {}) },
    lang: language
  };
}

export function sectionTitleFor(code, sectionId) {
  return docStrings(code).sectionTitles[sectionId] ?? sectionId;
}

// ---------------------------------------------------------------------------
// Données visibles (annexe + lecture) et guide d'adaptation culturelle.
// ---------------------------------------------------------------------------

const DETAILS = {
  fr: {
    styleGuide:
      "Écris comme un auteur francophone natif : ton chaleureux, tutoiement, phrases fluides et concrètes. Évite les tournures traduites de l'anglais. Adapte les exemples à la culture francophone (rapport à la famille, au travail, à la spiritualité).",
    planets: { Sun: "Soleil", Moon: "Lune", Mercury: "Mercure", Venus: "Vénus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturne" },
    signs: {
      Aries: "Bélier", Taurus: "Taureau", Gemini: "Gémeaux", Cancer: "Cancer", Leo: "Lion", Virgo: "Vierge",
      Libra: "Balance", Scorpio: "Scorpion", Sagittarius: "Sagittaire", Capricorn: "Capricorne", Aquarius: "Verseau", Pisces: "Poissons"
    },
    labels: {
      date: "Date de naissance", time: "Heure de naissance", timeInterval: "Heure de naissance (intervalle)",
      place: "Lieu de naissance", tz: "Fuseau horaire", coords: "Coordonnées", zodiac: "Zodiaque",
      houses: "Système de maisons", sect: "Secte du thème", interval: "Analyse d'intervalle", person: "Personne",
      house: "maison", retro: "rétrograde", asc: "Ascendant", mc: "Milieu du Ciel", aspect: "distance angulaire",
      closest: "plus proche candidat", gap: "écart", noOrb: "aucune règle d'orbe active",
      stable: "cible(s) stable(s)", sensitive: "sensible(s)", indeterminate: "indéterminée(s)"
    },
    values: {
      tropical: "tropical", wholeSign: "Whole Sign (maisons entières)", wholeSignShort: "Whole Sign",
      diurnal: "diurne (Soleil au-dessus de l'horizon)", nocturnal: "nocturne (Soleil sous l'horizon)",
      exact: "exacte", approximate: "approximative", unknown: "inconnue"
    },
    uncertainty: {
      unknown: "Heure de naissance inconnue : l'Ascendant, le Milieu du Ciel, les maisons et la secte n'ont pas été calculés.",
      approximate: "Heure de naissance approximative : l'Ascendant et les maisons dépendent d'une marge d'incertitude inconnue.",
      interval: "Heure de naissance fournie en intervalle : aucune heure exacte n'a été inventée."
    }
  },
  en: {
    styleGuide:
      "Write as a native English author: warm, natural, flowing sentences with 'you'. Do not translate French structures or idioms. Adapt examples to the reader's culture (family, work, spirituality).",
    planets: { Sun: "Sun", Moon: "Moon", Mercury: "Mercury", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
    signs: {
      Aries: "Aries", Taurus: "Taurus", Gemini: "Gemini", Cancer: "Cancer", Leo: "Leo", Virgo: "Virgo",
      Libra: "Libra", Scorpio: "Scorpio", Sagittarius: "Sagittarius", Capricorn: "Capricorn", Aquarius: "Aquarius", Pisces: "Pisces"
    },
    labels: {
      date: "Date of birth", time: "Time of birth", timeInterval: "Time of birth (range)",
      place: "Place of birth", tz: "Time zone", coords: "Coordinates", zodiac: "Zodiac",
      houses: "House system", sect: "Chart sect", interval: "Range analysis", person: "Person",
      house: "house", retro: "retrograde", asc: "Ascendant", mc: "Midheaven", aspect: "angular distance",
      closest: "closest candidate", gap: "gap", noOrb: "no orb rule active",
      stable: "stable target(s)", sensitive: "sensitive", indeterminate: "indeterminate"
    },
    values: {
      tropical: "tropical", wholeSign: "Whole Sign houses", wholeSignShort: "Whole Sign",
      diurnal: "diurnal (Sun above the horizon)", nocturnal: "nocturnal (Sun below the horizon)",
      exact: "exact", approximate: "approximate", unknown: "unknown"
    },
    uncertainty: {
      unknown: "Birth time unknown: the Ascendant, Midheaven, houses and sect were not calculated.",
      approximate: "Approximate birth time: the Ascendant and houses depend on an unknown margin of uncertainty.",
      interval: "Birth time given as a range: no exact time was invented."
    }
  },
  de: {
    styleGuide:
      "Schreibe wie ein deutschsprachiger Autor: klar, warm und gut gegliedert, mit 'du'. Keine französischen Wendungen. Beispiele an die deutschsprachige Kultur anpassen (Familie, Arbeit, Spiritualität).",
    planets: { Sun: "Sonne", Moon: "Mond", Mercury: "Merkur", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
    signs: {
      Aries: "Widder", Taurus: "Stier", Gemini: "Zwillinge", Cancer: "Krebs", Leo: "Löwe", Virgo: "Jungfrau",
      Libra: "Waage", Scorpio: "Skorpion", Sagittarius: "Schütze", Capricorn: "Steinbock", Aquarius: "Wassermann", Pisces: "Fische"
    },
    labels: {
      date: "Geburtsdatum", time: "Geburtszeit", timeInterval: "Geburtszeit (Zeitspanne)",
      place: "Geburtsort", tz: "Zeitzone", coords: "Koordinaten", zodiac: "Tierkreis",
      houses: "Häusersystem", sect: "Sekt des Horoskops", interval: "Zeitspannen-Analyse", person: "Person",
      house: "Haus", retro: "rückläufig", asc: "Aszendent", mc: "Medium Coeli", aspect: "Winkelabstand",
      closest: "nächster Kandidat", gap: "Abweichung", noOrb: "keine Orbis-Regel aktiv",
      stable: "stabile(s) Ziel(e)", sensitive: "sensibel", indeterminate: "unbestimmt"
    },
    values: {
      tropical: "tropisch", wholeSign: "Ganzzeichen-Häuser", wholeSignShort: "Ganzzeichen",
      diurnal: "Taggeburt (Sonne über dem Horizont)", nocturnal: "Nachtgeburt (Sonne unter dem Horizont)",
      exact: "genau", approximate: "ungefähr", unknown: "unbekannt"
    },
    uncertainty: {
      unknown: "Geburtszeit unbekannt: Aszendent, Medium Coeli, Häuser und Sekt wurden nicht berechnet.",
      approximate: "Ungefähre Geburtszeit: Aszendent und Häuser hängen von einer unbekannten Unsicherheit ab.",
      interval: "Geburtszeit als Zeitspanne angegeben: es wurde keine genaue Uhrzeit erfunden."
    }
  },
  es: {
    styleGuide:
      "Escribe como un autor hispanohablante nativo: tono cálido, natural y fluido, con 'tú'. Evita calcos del francés. Adapta los ejemplos a la cultura hispanohablante (familia, trabajo, espiritualidad).",
    planets: { Sun: "Sol", Moon: "Luna", Mercury: "Mercurio", Venus: "Venus", Mars: "Marte", Jupiter: "Júpiter", Saturn: "Saturno" },
    signs: {
      Aries: "Aries", Taurus: "Tauro", Gemini: "Géminis", Cancer: "Cáncer", Leo: "Leo", Virgo: "Virgo",
      Libra: "Libra", Scorpio: "Escorpio", Sagittarius: "Sagitario", Capricorn: "Capricornio", Aquarius: "Acuario", Pisces: "Piscis"
    },
    labels: {
      date: "Fecha de nacimiento", time: "Hora de nacimiento", timeInterval: "Hora de nacimiento (intervalo)",
      place: "Lugar de nacimiento", tz: "Zona horaria", coords: "Coordenadas", zodiac: "Zodíaco",
      houses: "Sistema de casas", sect: "Secta de la carta", interval: "Análisis del intervalo", person: "Persona",
      house: "casa", retro: "retrógrado", asc: "Ascendente", mc: "Medio Cielo", aspect: "distancia angular",
      closest: "candidato más cercano", gap: "desviación", noOrb: "ninguna regla de orbe activa",
      stable: "objetivo(s) estable(s)", sensitive: "sensible(s)", indeterminate: "indeterminado(s)"
    },
    values: {
      tropical: "tropical", wholeSign: "casas por signos enteros", wholeSignShort: "signos enteros",
      diurnal: "diurna (Sol sobre el horizonte)", nocturnal: "nocturna (Sol bajo el horizonte)",
      exact: "exacta", approximate: "aproximada", unknown: "desconocida"
    },
    uncertainty: {
      unknown: "Hora de nacimiento desconocida: no se calcularon el Ascendente, el Medio Cielo, las casas ni la secta.",
      approximate: "Hora de nacimiento aproximada: el Ascendente y las casas dependen de un margen de incertidumbre desconocido.",
      interval: "Hora de nacimiento dada como intervalo: no se inventó ninguna hora exacta."
    }
  },
  it: {
    styleGuide:
      "Scrivi come un autore italiano madrelingua: tono caldo, naturale e scorrevole, con 'tu'. Evita calchi dal francese. Adatta gli esempi alla cultura italiana (famiglia, lavoro, spiritualità).",
    planets: { Sun: "Sole", Moon: "Luna", Mercury: "Mercurio", Venus: "Venere", Mars: "Marte", Jupiter: "Giove", Saturn: "Saturno" },
    signs: {
      Aries: "Ariete", Taurus: "Toro", Gemini: "Gemelli", Cancer: "Cancro", Leo: "Leone", Virgo: "Vergine",
      Libra: "Bilancia", Scorpio: "Scorpione", Sagittarius: "Sagittario", Capricorn: "Capricorno", Aquarius: "Acquario", Pisces: "Pesci"
    },
    labels: {
      date: "Data di nascita", time: "Ora di nascita", timeInterval: "Ora di nascita (intervallo)",
      place: "Luogo di nascita", tz: "Fuso orario", coords: "Coordinate", zodiac: "Zodiaco",
      houses: "Sistema delle case", sect: "Setta del tema", interval: "Analisi dell'intervallo", person: "Persona",
      house: "casa", retro: "retrogrado", asc: "Ascendente", mc: "Medio Cielo", aspect: "distanza angolare",
      closest: "candidato più vicino", gap: "scarto", noOrb: "nessuna regola di orbe attiva",
      stable: "obiettivo/i stabile/i", sensitive: "sensibile/i", indeterminate: "indeterminato/i"
    },
    values: {
      tropical: "tropicale", wholeSign: "case a segno intero", wholeSignShort: "segno intero",
      diurnal: "diurna (Sole sopra l'orizzonte)", nocturnal: "notturna (Sole sotto l'orizzonte)",
      exact: "esatta", approximate: "approssimativa", unknown: "sconosciuta"
    },
    uncertainty: {
      unknown: "Ora di nascita sconosciuta: Ascendente, Medio Cielo, case e setta non sono stati calcolati.",
      approximate: "Ora di nascita approssimativa: Ascendente e case dipendono da un margine di incertezza sconosciuto.",
      interval: "Ora di nascita indicata come intervallo: nessuna ora esatta è stata inventata."
    }
  }
};

export function localeDetails(code) {
  return DETAILS[normalizeLanguage(code)] ?? DETAILS.fr;
}
