// Traductions du parcours public (interface + documents générés).
// Les directives envoyées au modèle restent en français ; le texte produit suit
// la langue choisie par le visiteur.

export const LANGUAGES = Object.freeze([
  { code: "fr", label: "Français", flag: "🇫🇷", englishName: "French" },
  { code: "en", label: "English", flag: "🇬🇧", englishName: "English" },
  { code: "de", label: "Deutsch", flag: "🇩🇪", englishName: "German" },
  { code: "es", label: "Español", flag: "🇪🇸", englishName: "Spanish" },
  { code: "it", label: "Italiano", flag: "🇮🇹", englishName: "Italian" },
  { code: "pt", label: "Português", flag: "🇵🇹", englishName: "Portuguese" },
  { code: "no", label: "Norsk", flag: "🇳🇴", englishName: "Norwegian" },
  { code: "da", label: "Dansk", flag: "🇩🇰", englishName: "Danish" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱", englishName: "Dutch" }
]);

export function isSupportedLanguage(code) {
  return LANGUAGES.some((entry) => entry.code === code);
}

export function normalizeLanguage(code) {
  const value = String(code ?? "").slice(0, 2).toLowerCase();
  return isSupportedLanguage(value) ? value : "fr";
}

export function englishNameFor(code) {
  return LANGUAGES.find((entry) => entry.code === normalizeLanguage(code))?.englishName ?? "French";
}

const FR = {
  brand: "Lastro · Lecture symbolique personnalisée",
  person: "Personne",
  generatedOn: "Généré le",
  caveat:
    "Cadre : cette lecture est une cartographie intérieure, symbolique et non prédictive. Elle ne constitue ni un diagnostic, ni une thérapie, ni une prédiction d'événements. Le libre arbitre reste entier. Les données astronomiques utilisées sont vérifiées (annexe technique) ; les interprétations restent des lectures symboliques.",
  writerNoteLlm: "Rédaction : rédacteur IA configuré, sections validées par la machine avant relecture humaine.",
  writerNoteTemplate: "Brouillon : rédacteur IA non configuré (clé absente). Ce document n'est pas prêt pour la livraison.",
  footer:
    "Document produit par Lastro — positions astronomiques calculées localement, interprétation symbolique.",
  badgeCalculated: "Données vérifiées (calcul)",
  badgeSymbolic: "Lecture symbolique",
  badgeUnavailable: "Module non disponible dans cette version",
  statusOk: "validé machine",
  statusNeedsReview: "à vérifier",
  statusNotAvailable: "non disponible",
  statusTemplateDraft: "brouillon (sans rédacteur IA)",
  statusLabelPrefix: "Statut",
  annexShow: "Voir les données astronomiques utilisées",
  ethicalClosing: "Cette lecture est symbolique : elle propose des pistes de réflexion, pas des vérités ni des prédictions. Vous restez seul juge de ce qui vous correspond.",
  annexTitle: "Annexe — socle de calcul vérifié",
  annexIntro:
    "Cette annexe contient les seules données calculées et vérifiées utilisées pour ce dossier. Aucune interprétation n'y figure.",
  uncertaintyLimits: "Limites d'incertitude",
  engineWarnings: "Avertissements du moteur de calcul",
  unavailableText:
    "Aucune prédiction d'événement n'est produite : ce module livrera des fenêtres larges, des thèmes de maturation et des postures intérieures (0–1 an, 1–3 ans, 3–5 ans).",
  titlePrefix: "Lecture symbolique",
  sectionTitles: {
    introduction: "Votre ciel en un coup d'œil",
    "position-naissance-axe": "Votre identité et votre manière de vous exprimer",
    "structure-psychologique": "Vos émotions",
    transgenerationnel: "Lecture transgénérationnelle",
    "archetypes-dominants": "Archétypes dominants",
    "grandes-lignes": "Vos grandes lignes",
    "lecture-passe": "Votre passé",
    "lettre-ame": "Lettre d'âme",
    "lettre-miroir": "Lettre miroir",
    "periodes-cycles": "Périodes & Cycles",
    "cles-integration": "Clés d'intégration",
    "conclusion-ethique": "Conclusion éthique",
    "relations": "Vos relations",
    "action": "Votre manière d'agir",
    "forces-tensions": "Vos forces et vos tensions"
  }
};

const EN = {
  brand: "Lastro · Personalised symbolic reading",
  person: "Person",
  generatedOn: "Generated on",
  caveat:
    "Scope: this reading is an inner, symbolic and non-predictive map. It is neither a diagnosis, nor therapy, nor a prediction of events. Free will remains fully yours. The astronomical data used is verified (technical annex); the interpretations remain symbolic readings.",
  writerNoteLlm: "Writing: AI writer configured, sections machine-validated before human review.",
  writerNoteTemplate: "Draft: AI writer not configured (no key). This document is not ready for delivery.",
  footer:
    "Document generated by Lastro — local and deterministic calculation base; every interpretation is labelled and must be reviewed before delivery.",
  badgeCalculated: "Verified data (calculation)",
  badgeSymbolic: "Symbolic reading",
  badgeUnavailable: "Module not available in this version",
  statusOk: "machine-validated",
  statusNeedsReview: "to review",
  statusNotAvailable: "not available",
  statusTemplateDraft: "draft (no AI writer)",
  statusLabelPrefix: "Status",
  annexShow: "See the astronomical data used",
  ethicalClosing: "This reading is symbolic: it offers paths for reflection, not truths or predictions. You remain the only judge of what fits you.",
  annexTitle: "Technical annex — verified calculation base",
  annexIntro: "This annex contains the only calculated and verified data used for this reading. No interpretation appears here.",
  uncertaintyLimits: "Uncertainty limits",
  engineWarnings: "Calculation engine warnings",
  unavailableText:
    "No event prediction is produced: this module will provide broad windows, maturation themes and inner postures (0–1 year, 1–3 years, 3–5 years).",
  titlePrefix: "Symbolic reading",
  sectionTitles: {
    introduction: "Your sky at a glance",
    "position-naissance-axe": "Your identity and how you express it",
    "structure-psychologique": "Your emotions",
    transgenerationnel: "Transgenerational reading",
    "archetypes-dominants": "Dominant archetypes",
    "grandes-lignes": "Your main threads",
    "lecture-passe": "Your past",
    "lettre-ame": "Soul letter",
    "lettre-miroir": "Mirror letter",
    "periodes-cycles": "Periods & Cycles",
    "cles-integration": "Keys to integration",
    "conclusion-ethique": "Ethical conclusion",
    "relations": "Your relationships",
    "action": "How you take action",
    "forces-tensions": "Your strengths and tensions"
  }
};

const DE = {
  brand: "Lastro · Persönliche symbolische Deutung",
  person: "Person",
  generatedOn: "Erstellt am",
  caveat:
    "Rahmen: Diese Deutung ist eine innere, symbolische und nicht vorhersagende Landkarte. Sie ist weder eine Diagnose noch eine Therapie noch eine Vorhersage von Ereignissen. Dein freier Wille bleibt vollständig erhalten. Die verwendeten astronomischen Daten sind geprüft (technischer Anhang); die Deutungen bleiben symbolisch.",
  writerNoteLlm: "Text: KI-Autor konfiguriert, Abschnitte vor der menschlichen Prüfung maschinell validiert.",
  writerNoteTemplate: "Entwurf: Kein KI-Autor konfiguriert (kein Schlüssel). Dieses Dokument ist nicht lieferbereit.",
  footer:
    "Von Lastro erstelltes Dokument — lokale und deterministische Berechnungsgrundlage; jede Deutung ist gekennzeichnet und vor der Auslieferung zu prüfen.",
  badgeCalculated: "Geprüfte Daten (Berechnung)",
  badgeSymbolic: "Symbolische Deutung",
  badgeUnavailable: "Modul in dieser Version nicht verfügbar",
  statusOk: "maschinell validiert",
  statusNeedsReview: "zu prüfen",
  statusNotAvailable: "nicht verfügbar",
  statusTemplateDraft: "Entwurf (ohne KI-Autor)",
  statusLabelPrefix: "Status",
  annexShow: "Verwendete astronomische Daten ansehen",
  ethicalClosing: "Diese Lesung ist symbolisch: sie bietet Denkanstöße, keine Wahrheiten und keine Vorhersagen. Du bleibst der einzige Richter darüber, was zu dir passt.",
  annexTitle: "Technischer Anhang — geprüfte Berechnungsgrundlage",
  annexIntro: "Dieser Anhang enthält nur die berechneten und geprüften Daten dieser Deutung. Es steht keine Interpretation darin.",
  uncertaintyLimits: "Unsicherheitsgrenzen",
  engineWarnings: "Hinweise der Berechnungs-Engine",
  unavailableText:
    "Es werden keine Ereignisse vorhergesagt: Dieses Modul liefert breite Zeitfenster, Reifethemen und innere Haltungen (0–1 Jahr, 1–3 Jahre, 3–5 Jahre).",
  titlePrefix: "Symbolische Deutung",
  sectionTitles: {
    introduction: "Dein Himmel auf einen Blick",
    "position-naissance-axe": "Deine Identität und dein Ausdruck",
    "structure-psychologique": "Deine Gefühle",
    transgenerationnel: "Transgenerationale Deutung",
    "archetypes-dominants": "Dominante Archetypen",
    "grandes-lignes": "Deine großen Linien",
    "lecture-passe": "Deine Vergangenheit",
    "lettre-ame": "Seelenbrief",
    "lettre-miroir": "Spiegelbrief",
    "periodes-cycles": "Phasen & Zyklen",
    "cles-integration": "Schlüssel zur Integration",
    "conclusion-ethique": "Ethischer Abschluss",
    "relations": "Deine Beziehungen",
    "action": "Wie du handelst",
    "forces-tensions": "Deine Stärken und Spannungen"
  }
};

const ES = {
  brand: "Lastro · Lectura simbólica personalizada",
  person: "Persona",
  generatedOn: "Generado el",
  caveat:
    "Marco: esta lectura es un mapa interior, simbólico y no predictivo. No constituye un diagnóstico, ni una terapia, ni una predicción de acontecimientos. El libre albedrío permanece intacto. Los datos astronómicos utilizados están verificados (anexo técnico); las interpretaciones siguen siendo lecturas simbólicas.",
  writerNoteLlm: "Redacción: redactor IA configurado, secciones validadas por la máquina antes de la revisión humana.",
  writerNoteTemplate: "Borrador: redactor IA no configurado (sin clave). Este documento no está listo para entregar.",
  footer:
    "Documento generado por Lastro — base de cálculo local y determinista; toda interpretación está etiquetada y debe revisarse antes de la entrega.",
  badgeCalculated: "Datos verificados (cálculo)",
  badgeSymbolic: "Lectura simbólica",
  badgeUnavailable: "Módulo no disponible en esta versión",
  statusOk: "validado por máquina",
  statusNeedsReview: "por revisar",
  statusNotAvailable: "no disponible",
  statusTemplateDraft: "borrador (sin redactor IA)",
  statusLabelPrefix: "Estado",
  annexShow: "Ver los datos astronómicos utilizados",
  ethicalClosing: "Esta lectura es simbólica: propone pistas de reflexión, no verdades ni predicciones. Tú sigues siendo el único juez de lo que te corresponde.",
  annexTitle: "Anexo técnico — base de cálculo verificada",
  annexIntro: "Este anexo contiene únicamente los datos calculados y verificados de esta lectura. No figura ninguna interpretación.",
  uncertaintyLimits: "Límites de incertidumbre",
  engineWarnings: "Avisos del motor de cálculo",
  unavailableText:
    "No se predice ningún acontecimiento: este módulo ofrecerá ventanas amplias, temas de maduración y posturas interiores (0–1 año, 1–3 años, 3–5 años).",
  titlePrefix: "Lectura simbólica",
  sectionTitles: {
    introduction: "Tu cielo de un vistazo",
    "position-naissance-axe": "Tu identidad y tu forma de expresarte",
    "structure-psychologique": "Tus emociones",
    transgenerationnel: "Lectura transgeneracional",
    "archetypes-dominants": "Arquetipos dominantes",
    "grandes-lignes": "Tus grandes líneas",
    "lecture-passe": "Tu pasado",
    "lettre-ame": "Carta del alma",
    "lettre-miroir": "Carta espejo",
    "periodes-cycles": "Períodos y ciclos",
    "cles-integration": "Claves de integración",
    "conclusion-ethique": "Conclusión ética",
    "relations": "Tus relaciones",
    "action": "Tu manera de actuar",
    "forces-tensions": "Tus fuerzas y tus tensiones"
  }
};

const IT = {
  brand: "Lastro · Lettura simbolica personalizzata",
  person: "Persona",
  generatedOn: "Generato il",
  caveat:
    "Quadro: questa lettura è una mappa interiore, simbolica e non predittiva. Non è una diagnosi, né una terapia, né una previsione di eventi. Il libero arbitrio resta intero. I dati astronomici utilizzati sono verificati (appendice tecnica); le interpretazioni restano letture simboliche.",
  writerNoteLlm: "Scrittura: autore IA configurato, sezioni validate dalla macchina prima della revisione umana.",
  writerNoteTemplate: "Bozza: autore IA non configurato (chiave assente). Questo documento non è pronto per la consegna.",
  footer:
    "Documento generato da Lastro — base di calcolo locale e deterministica; ogni interpretazione è etichettata e va rivista prima della consegna.",
  badgeCalculated: "Dati verificati (calcolo)",
  badgeSymbolic: "Lettura simbolica",
  badgeUnavailable: "Modulo non disponibile in questa versione",
  statusOk: "validato dalla macchina",
  statusNeedsReview: "da rivedere",
  statusNotAvailable: "non disponibile",
  statusTemplateDraft: "bozza (senza autore IA)",
  statusLabelPrefix: "Stato",
  annexShow: "Vedi i dati astronomici utilizzati",
  ethicalClosing: "Questa lettura è simbolica: propone spunti di riflessione, non verità né previsioni. Resti tu l'unico giudice di ciò che ti corrisponde.",
  annexTitle: "Appendice tecnica — base di calcolo verificata",
  annexIntro: "Questa appendice contiene solo i dati calcolati e verificati di questa lettura. Non contiene alcuna interpretazione.",
  uncertaintyLimits: "Limiti di incertezza",
  engineWarnings: "Avvisi del motore di calcolo",
  unavailableText:
    "Non viene prodotta alcuna previsione di eventi: questo modulo offrirà finestre ampie, temi di maturazione e posture interiori (0–1 anno, 1–3 anni, 3–5 anni).",
  titlePrefix: "Lettura simbolica",
  sectionTitles: {
    introduction: "Il tuo cielo in breve",
    "position-naissance-axe": "La tua identità e il tuo modo di esprimerti",
    "structure-psychologique": "Le tue emozioni",
    transgenerationnel: "Lettura transgenerazionale",
    "archetypes-dominants": "Archetipi dominanti",
    "grandes-lignes": "Le tue grandi linee",
    "lecture-passe": "Il tuo passato",
    "lettre-ame": "Lettera dell'anima",
    "lettre-miroir": "Lettera specchio",
    "periodes-cycles": "Periodi e cicli",
    "cles-integration": "Chiavi di integrazione",
    "conclusion-ethique": "Conclusione etica",
    "relations": "Le tue relazioni",
    "action": "Il tuo modo di agire",
    "forces-tensions": "I tuoi punti di forza e le tue tensioni"
  }
};

const DOCS = { fr: FR, en: EN, de: DE, es: ES, it: IT };

// ---------------------------------------------------------------------------
// Marge d'incertitude (heure approximative) — 9 langues.
//
// Ces chaînes portent le plafond de langage : la marge est écrite, et un signe
// qui change à l'intérieur de la marge est déclaré NON DÉCIDABLE. Elles vivent
// dans une table unique, fusionnée en profondeur, pour que les quatre langues
// sans table `DETAILS` complète (pt, no, da, nl) les reçoivent aussi.
// ---------------------------------------------------------------------------
const MARGIN_STRINGS = {
  fr: {
    margin: "Marge d'incertitude retenue",
    marginRange: "Plage calculée sur la marge",
    marginDefault: "±{n} min (valeur par défaut Lastro, non précisée par le client)",
    marginSupplied: "±{n} min (précisée par le client)",
    signStable: "signe stable sur toute la marge",
    signNotDecidable: "signe non décidable : la frontière est franchie dans la marge",
    signNotEstablished: "signe non établi sans heure précise",
    probable: "probable",
    signNotDecidableShort: "non décidable",
    withinMargin: "sur la marge ±{n} min",
    approximate:
      "Heure de naissance approximative : l'Ascendant, le Milieu du Ciel, les maisons et la secte ont été calculés sur la marge déclarée {margin}.",
    approximateStable:
      "Sur toute cette marge, le signe de l'Ascendant reste {sign} : il est donné comme probable, jamais comme exact.",
    approximateUnstable:
      "Le signe de l'Ascendant change dans cette marge ({from} → {to}) : il n'est pas décidable, et les maisons non plus.",
    approximateBodySigns: "Ces corps changent aussi de signe dans la marge : {bodies}.",
    approximateSect: "La secte (diurne ou nocturne) bascule dans cette marge : elle n'est pas affichée."
  },
  en: {
    margin: "Uncertainty margin used",
    marginRange: "Range computed over the margin",
    marginDefault: "±{n} min (Lastro default, not specified by the client)",
    marginSupplied: "±{n} min (specified by the client)",
    signStable: "sign stable across the whole margin",
    signNotDecidable: "sign not decidable: the boundary is crossed within the margin",
    signNotEstablished: "sign not established without a precise time",
    probable: "likely",
    signNotDecidableShort: "not decidable",
    withinMargin: "over the ±{n} min margin",
    approximate:
      "Approximate birth time: the Ascendant, the Midheaven, the houses and the sect were computed over the declared margin {margin}.",
    approximateStable: "Across this whole margin, the Ascendant sign remains {sign}: it is given as probable, never as exact.",
    approximateUnstable:
      "The Ascendant sign changes within this margin ({from} → {to}): it is not decidable, and neither are the houses.",
    approximateBodySigns: "These bodies also change sign within the margin: {bodies}.",
    approximateSect: "The sect (diurnal or nocturnal) switches within this margin: it is not displayed."
  },
  de: {
    margin: "Angesetzte Unsicherheitsspanne",
    marginRange: "Über die Spanne berechneter Bereich",
    marginDefault: "±{n} Min. (Standardwert von Lastro, vom Kunden nicht angegeben)",
    marginSupplied: "±{n} Min. (vom Kunden angegeben)",
    signStable: "Zeichen über die gesamte Spanne stabil",
    signNotDecidable: "Zeichen nicht entscheidbar: die Grenze wird innerhalb der Spanne überschritten",
    signNotEstablished: "Zeichen ohne genaue Geburtszeit nicht bestimmbar",
    probable: "wahrscheinlich",
    signNotDecidableShort: "nicht entscheidbar",
    withinMargin: "über die Spanne von ±{n} Min.",
    approximate:
      "Ungefähre Geburtszeit: Aszendent, Medium Coeli, Häuser und Sekte wurden über die angegebene Spanne {margin} berechnet.",
    approximateStable: "Über diese gesamte Spanne bleibt das Zeichen des Aszendenten {sign}: es wird als wahrscheinlich angegeben, nie als exakt.",
    approximateUnstable:
      "Das Zeichen des Aszendenten ändert sich innerhalb dieser Spanne ({from} → {to}): es ist nicht entscheidbar, und die Häuser ebenso wenig.",
    approximateBodySigns: "Auch diese Himmelskörper wechseln innerhalb der Spanne das Zeichen: {bodies}.",
    approximateSect: "Die Sekte (Tag oder Nacht) wechselt innerhalb dieser Spanne: sie wird nicht angezeigt."
  },
  es: {
    margin: "Margen de incertidumbre considerado",
    marginRange: "Rango calculado sobre el margen",
    marginDefault: "±{n} min (valor predeterminado de Lastro, no indicado por el cliente)",
    marginSupplied: "±{n} min (indicado por el cliente)",
    signStable: "signo estable en todo el margen",
    signNotDecidable: "signo no decidible: se cruza la frontera dentro del margen",
    signNotEstablished: "signo no establecido sin hora precisa",
    probable: "probable",
    signNotDecidableShort: "no decidible",
    withinMargin: "sobre el margen de ±{n} min",
    approximate:
      "Hora de nacimiento aproximada: el Ascendente, el Medio Cielo, las casas y la secta se han calculado sobre el margen declarado {margin}.",
    approximateStable: "En todo este margen, el signo del Ascendente sigue siendo {sign}: se da como probable, nunca como exacto.",
    approximateUnstable:
      "El signo del Ascendente cambia dentro de este margen ({from} → {to}): no es decidible, y las casas tampoco.",
    approximateBodySigns: "Estos cuerpos también cambian de signo dentro del margen: {bodies}.",
    approximateSect: "La secta (diurna o nocturna) cambia dentro de este margen: no se muestra."
  },
  it: {
    margin: "Margine di incertezza adottato",
    marginRange: "Intervallo calcolato sul margine",
    marginDefault: "±{n} min (valore predefinito di Lastro, non indicato dal cliente)",
    marginSupplied: "±{n} min (indicato dal cliente)",
    signStable: "segno stabile su tutto il margine",
    signNotDecidable: "segno non decidibile: il confine viene superato entro il margine",
    signNotEstablished: "segno non stabilito senza ora precisa",
    probable: "probabile",
    signNotDecidableShort: "non decidibile",
    withinMargin: "sul margine di ±{n} min",
    approximate:
      "Ora di nascita approssimativa: l'Ascendente, il Medio Cielo, le case e la setta sono stati calcolati sul margine dichiarato {margin}.",
    approximateStable: "Su tutto questo margine, il segno dell'Ascendente resta {sign}: viene indicato come probabile, mai come esatto.",
    approximateUnstable: "Il segno dell'Ascendente cambia entro questo margine ({from} → {to}): non è decidibile, e nemmeno le case.",
    approximateBodySigns: "Anche questi corpi cambiano segno entro il margine: {bodies}.",
    approximateSect: "La setta (diurna o notturna) cambia entro questo margine: non viene mostrata."
  },
  pt: {
    margin: "Margem de incerteza adotada",
    marginRange: "Intervalo calculado sobre a margem",
    marginDefault: "±{n} min (valor padrão da Lastro, não informado pelo cliente)",
    marginSupplied: "±{n} min (informado pelo cliente)",
    signStable: "signo estável em toda a margem",
    signNotDecidable: "signo não decidível: a fronteira é ultrapassada dentro da margem",
    signNotEstablished: "signo não estabelecido sem hora precisa",
    probable: "provável",
    signNotDecidableShort: "não decidível",
    withinMargin: "sobre a margem de ±{n} min",
    approximate:
      "Hora de nascimento aproximada: o Ascendente, o Meio do Céu, as casas e a seita foram calculados sobre a margem declarada {margin}.",
    approximateStable: "Em toda esta margem, o signo do Ascendente permanece {sign}: ele é apresentado como provável, nunca como exato.",
    approximateUnstable: "O signo do Ascendente muda dentro desta margem ({from} → {to}): ele não é decidível, e as casas também não.",
    approximateBodySigns: "Estes corpos também mudam de signo dentro da margem: {bodies}.",
    approximateSect: "A seita (diurna ou noturna) muda dentro desta margem: ela não é exibida."
  },
  no: {
    margin: "Usikkerhetsmargen som er lagt til grunn",
    marginRange: "Område beregnet over marginen",
    marginDefault: "±{n} min (standardverdi fra Lastro, ikke oppgitt av kunden)",
    marginSupplied: "±{n} min (oppgitt av kunden)",
    signStable: "tegnet stabilt over hele marginen",
    signNotDecidable: "tegnet ikke avgjørbart: grensen krysses innenfor marginen",
    signNotEstablished: "tegnet ikke fastslått uten presis tid",
    probable: "sannsynlig",
    signNotDecidableShort: "ikke avgjørbart",
    withinMargin: "over marginen på ±{n} min",
    approximate:
      "Omtrentlig fødselstid: Ascendanten, Midtheaven, husene og sekten er beregnet over den oppgitte marginen {margin}.",
    approximateStable: "Over hele denne marginen forblir Ascendantens tegn {sign}: det oppgis som sannsynlig, aldri som eksakt.",
    approximateUnstable:
      "Ascendantens tegn endres innenfor denne marginen ({from} → {to}): det er ikke avgjørbart, og heller ikke husene.",
    approximateBodySigns: "Disse himmellegemene skifter også tegn innenfor marginen: {bodies}.",
    approximateSect: "Sekten (dag eller natt) skifter innenfor denne marginen: den vises ikke."
  },
  da: {
    margin: "Usikkerhedsmargin anvendt",
    marginRange: "Interval beregnet over marginen",
    marginDefault: "±{n} min (standardværdi fra Lastro, ikke oplyst af kunden)",
    marginSupplied: "±{n} min (oplyst af kunden)",
    signStable: "tegnet stabilt over hele marginen",
    signNotDecidable: "tegnet ikke afgørbart: grænsen overskrides inden for marginen",
    signNotEstablished: "tegnet ikke fastslått uden præcis tid",
    probable: "sandsynlig",
    signNotDecidableShort: "ikke afgørbart",
    withinMargin: "over marginen på ±{n} min",
    approximate:
      "Omtrentligt fødselstidspunkt: Ascendanten, Midterhimlen, husene og sekten er beregnet over den oplyste margin {margin}.",
    approximateStable: "Over hele denne margin forbliver Ascendantens tegn {sign}: det angives som sandsynligt, aldrig som præcist.",
    approximateUnstable:
      "Ascendantens tegn skifter inden for denne margin ({from} → {to}): det er ikke afgørbart, og det er husene heller ikke.",
    approximateBodySigns: "Disse himmellegemer skifter også tegn inden for marginen: {bodies}.",
    approximateSect: "Sekten (dag eller nat) skifter inden for denne margin: den vises ikke."
  },
  nl: {
    margin: "Aangehouden onzekerheidsmarge",
    marginRange: "Bereik berekend over de marge",
    marginDefault: "±{n} min (standaardwaarde van Lastro, niet door de klant opgegeven)",
    marginSupplied: "±{n} min (door de klant opgegeven)",
    signStable: "teken stabiel over de hele marge",
    signNotDecidable: "teken niet te bepalen: de grens wordt binnen de marge overschreden",
    signNotEstablished: "teken niet vastgesteld zonder precieze tijd",
    probable: "waarschijnlijk",
    signNotDecidableShort: "niet te bepalen",
    withinMargin: "over de marge van ±{n} min",
    approximate:
      "Geboortetijd bij benadering: de Ascendant, de Midhemel, de huizen en de sekte zijn berekend over de opgegeven marge {margin}.",
    approximateStable: "Over deze hele marge blijft het teken van de Ascendant {sign}: het wordt als waarschijnlijk gegeven, nooit als exact.",
    approximateUnstable:
      "Het teken van de Ascendant verandert binnen deze marge ({from} → {to}): het is niet te bepalen, en de huizen evenmin.",
    approximateBodySigns: "Deze lichamen veranderen ook van teken binnen de marge: {bodies}.",
    approximateSect: "De sekte (dag of nacht) wisselt binnen deze marge: deze wordt niet weergegeven."
  }
};

// ---------------------------------------------------------------------------
// Aspects retenus — convention Lastro « lastro-aspects@1.0.0 ».
//
// Les orbes sont une convention de produit : le document écrit la version et le
// vocabulaire employé. En français, on écrit « trigone », jamais « trine ».
// ---------------------------------------------------------------------------
const ASPECT_STRINGS = {
  fr: {
    aspects: "Aspects retenus (convention Lastro)",
    aspectGeometry: "Géométrie angulaire examinée",
    orb: "orbe",
    withLuminaries: "avec le Soleil ou la Lune",
    aspectsSummary: "{examined} couples examinés · {retained} aspects retenus · {marginDiscarded} écartés par la marge",
    aspectNotStableWithinMargin: "Aspects écartés car ils ne tiennent pas sur toute la marge d'incertitude : {list}.",
    annexMethod: "Positions astronomiques calculées localement, sans accès Internet, avec astronomy-engine 2.1.19. Zodiaque tropical, maisons Whole Sign (maisons entières). Les aspects retenus suivent la convention Lastro versionnée indiquée ci-dessus ; aucune interprétation n'est produite par le moteur.",
    aspectNames: { conjunction: "conjonction", sextile: "sextile", square: "carré", trine: "trigone", opposition: "opposition" }
  },
  en: {
    aspects: "Retained aspects (Lastro convention)",
    aspectGeometry: "Angular geometry examined",
    orb: "orb",
    withLuminaries: "with the Sun or the Moon",
    aspectsSummary: "{examined} pairs examined · {retained} aspects retained · {marginDiscarded} discarded because of the margin",
    aspectNotStableWithinMargin: "Aspects discarded because they do not hold across the whole uncertainty margin: {list}.",
    annexMethod: "Astronomical positions computed locally, without Internet access, with astronomy-engine 2.1.19. Tropical zodiac, Whole Sign houses. Retained aspects follow the versioned Lastro convention shown above; no interpretation is produced by the engine.",
    aspectNames: { conjunction: "conjunction", sextile: "sextile", square: "square", trine: "trine", opposition: "opposition" }
  },
  de: {
    aspects: "Berücksichtigte Aspekte (Lastro-Konvention)",
    aspectGeometry: "Geprüfte Winkelgeometrie",
    orb: "Orbis",
    withLuminaries: "mit Sonne oder Mond",
    aspectsSummary: "{examined} geprüfte Paare · {retained} berücksichtigte Aspekte · {marginDiscarded} wegen der Spanne verworfen",
    aspectNotStableWithinMargin: "Aspekte verworfen, weil sie nicht über die gesamte Unsicherheitsspanne bestehen: {list}.",
    annexMethod: "Astronomische Positionen werden lokal und ohne Internetzugang mit astronomy-engine 2.1.19 berechnet. Tropischer Tierkreis, Ganzzeichenhäuser. Die berücksichtigten Aspekte folgen der oben genannten versionierten Lastro-Konvention; der Motor erzeugt keine Deutung.",
    aspectNames: { conjunction: "Konjunktion", sextile: "Sextil", square: "Quadrat", trine: "Trigon", opposition: "Opposition" }
  },
  es: {
    aspects: "Aspectos retenidos (convención Lastro)",
    aspectGeometry: "Geometría angular examinada",
    orb: "orbe",
    withLuminaries: "con el Sol o la Luna",
    aspectsSummary: "{examined} parejas examinadas · {retained} aspectos retenidos · {marginDiscarded} descartados por el margen",
    aspectNotStableWithinMargin: "Aspectos descartados porque no se mantienen en todo el margen de incertidumbre: {list}.",
    annexMethod: "Posiciones astronómicas calculadas localmente, sin acceso a Internet, con astronomy-engine 2.1.19. Zodíaco tropical, casas por signos enteros. Los aspectos retenidos siguen la convención Lastro versionada indicada arriba; el motor no produce ninguna interpretación.",
    aspectNames: { conjunction: "conjunción", sextile: "sextil", square: "cuadratura", trine: "trígono", opposition: "oposición" }
  },
  it: {
    aspects: "Aspetti ritenuti (convenzione Lastro)",
    aspectGeometry: "Geometria angolare esaminata",
    orb: "orbe",
    withLuminaries: "con il Sole o la Luna",
    aspectsSummary: "{examined} coppie esaminate · {retained} aspetti ritenuti · {marginDiscarded} scartati per il margine",
    aspectNotStableWithinMargin: "Aspetti scartati perché non reggono su tutto il margine di incertezza: {list}.",
    annexMethod: "Posizioni astronomiche calcolate localmente, senza accesso a Internet, con astronomy-engine 2.1.19. Zodiaco tropicale, case a segno intero. Gli aspetti ritenuti seguono la convenzione Lastro versionata indicata sopra; il motore non produce alcuna interpretazione.",
    aspectNames: { conjunction: "congiunzione", sextile: "sestile", square: "quadrato", trine: "trigono", opposition: "opposizione" }
  },
  pt: {
    aspects: "Aspetos retidos (convenção Lastro)",
    aspectGeometry: "Geometria angular examinada",
    orb: "orbe",
    withLuminaries: "com o Sol ou a Lua",
    aspectsSummary: "{examined} pares examinados · {retained} aspetos retidos · {marginDiscarded} descartados pela margem",
    aspectNotStableWithinMargin: "Aspetos descartados por não se manterem em toda a margem de incerteza: {list}.",
    annexMethod: "Posições astronómicas calculadas localmente, sem acesso à Internet, com astronomy-engine 2.1.19. Zodíaco tropical, casas por signos inteiros. Os aspetos retidos seguem a convenção Lastro versionada indicada acima; o motor não produz qualquer interpretação.",
    aspectNames: { conjunction: "conjunção", sextile: "sextil", square: "quadratura", trine: "trígono", opposition: "oposição" }
  },
  no: {
    aspects: "Aspekter som er lagt til grunn (Lastro-konvensjon)",
    aspectGeometry: "Undersøkt vinkelgeometri",
    orb: "orbis",
    withLuminaries: "med solen eller månen",
    aspectsSummary: "{examined} par undersøkt · {retained} aspekter lagt til grunn · {marginDiscarded} forkastet på grunn av marginen",
    aspectNotStableWithinMargin: "Aspekter forkastet fordi de ikke holder over hele usikkerhetsmargen: {list}.",
    annexMethod: "Astronomiske posisjoner beregnes lokalt, uten internettilgang, med astronomy-engine 2.1.19. Tropisk dyrekrets, heltegnshus. Aspektene som er lagt til grunn følger den versjonerte Lastro-konvensjonen ovenfor; motoren produserer ingen tolkning.",
    aspectNames: { conjunction: "konjunksjon", sextile: "sekstil", square: "kvadrat", trine: "trigon", opposition: "opposisjon" }
  },
  da: {
    aspects: "Aspekter der er lagt til grund (Lastro-konvention)",
    aspectGeometry: "Undersøgt vinkelgeometri",
    orb: "orbis",
    withLuminaries: "med solen eller månen",
    aspectsSummary: "{examined} par undersøgt · {retained} aspekter lagt til grund · {marginDiscarded} forkastet på grund af marginen",
    aspectNotStableWithinMargin: "Aspekter forkastet, fordi de ikke holder over hele usikkerhedsmarginen: {list}.",
    annexMethod: "Astronomiske positioner beregnes lokalt, uden internetadgang, med astronomy-engine 2.1.19. Tropisk dyrekrets, heltegnshuse. De aspekter, der er lagt til grund, følger den versionerede Lastro-konvention ovenfor; motoren producerer ingen fortolkning.",
    aspectNames: { conjunction: "konjunktion", sextile: "sekstil", square: "kvadrat", trine: "trigon", opposition: "opposition" }
  },
  nl: {
    aspects: "Aangehouden aspecten (Lastro-conventie)",
    aspectGeometry: "Onderzochte hoekgeometrie",
    orb: "orbe",
    withLuminaries: "met de zon of de maan",
    aspectsSummary: "{examined} paren onderzocht · {retained} aspecten aangehouden · {marginDiscarded} verworpen door de marge",
    aspectNotStableWithinMargin: "Aspecten verworpen omdat ze niet over de hele onzekerheidsmarge standhouden: {list}.",
    annexMethod: "Astronomische posities worden lokaal berekend, zonder internettoegang, met astronomy-engine 2.1.19. Tropische dierenriem, hele-tekenhuizen. De aangehouden aspecten volgen de hierboven genoemde geversioneerde Lastro-conventie; de engine produceert geen interpretatie.",
    aspectNames: { conjunction: "conjunctie", sextile: "sextiel", square: "vierkant", trine: "driehoek", opposition: "oppositie" }
  }
};


// En-tetes du tableau des positions. Les colonnes « maison » et « rétrograde »
// réutilisent les libellés existants : l'habillage les passe en majuscules.
const TABLE_STRINGS = {
  fr: { positions: "Positions calculées", planet: "Planète", sign: "Signe", degree: "Degré" },
  en: { positions: "Calculated positions", planet: "Planet", sign: "Sign", degree: "Degree" },
  de: { positions: "Berechnete Positionen", planet: "Planet", sign: "Zeichen", degree: "Grad" },
  es: { positions: "Posiciones calculadas", planet: "Planeta", sign: "Signo", degree: "Grado" },
  it: { positions: "Posizioni calcolate", planet: "Pianeta", sign: "Segno", degree: "Grado" },
  pt: { positions: "Posições calculadas", planet: "Planeta", sign: "Signo", degree: "Grau" },
  no: { positions: "Beregnede posisjoner", planet: "Planet", sign: "Tegn", degree: "Grad" },
  da: { positions: "Beregnede positioner", planet: "Planet", sign: "Tegn", degree: "Grad" },
  nl: { positions: "Berekende posities", planet: "Planeet", sign: "Teken", degree: "Graad" },
};

export function docStrings(code) {
  const language = normalizeLanguage(code);
  const table = DOCS[language] ?? FR;
  const details = DETAILS[language] ?? DETAILS.fr;
  const margin = MARGIN_STRINGS[language] ?? MARGIN_STRINGS.fr;
  const aspect = ASPECT_STRINGS[language] ?? ASPECT_STRINGS.fr;
  const tableStrings = TABLE_STRINGS[language] ?? TABLE_STRINGS.fr;
  const labels = {
    ...details.labels,
    margin: margin.margin,
    marginRange: margin.marginRange,
    aspects: aspect.aspects,
    positions: tableStrings.positions,
    aspectGeometry: aspect.aspectGeometry,
    orb: aspect.orb,
    planet: tableStrings.planet,
    sign: tableStrings.sign,
    degree: tableStrings.degree
  };
  const values = {
    ...details.values,
    marginDefault: margin.marginDefault,
    marginSupplied: margin.marginSupplied,
    signStable: margin.signStable,
    signNotDecidable: margin.signNotDecidable,
    signNotEstablished: margin.signNotEstablished,
    probable: margin.probable,
    signNotDecidableShort: margin.signNotDecidableShort,
    withinMargin: margin.withinMargin,
    withLuminaries: aspect.withLuminaries,
    aspectsSummary: aspect.aspectsSummary
  };
  const uncertainty = {
    ...details.uncertainty,
    approximate: margin.approximate,
    approximateStable: margin.approximateStable,
    approximateUnstable: margin.approximateUnstable,
    approximateBodySigns: margin.approximateBodySigns,
    approximateSect: margin.approximateSect,
    aspectNotStableWithinMargin: aspect.aspectNotStableWithinMargin
  };
  return {
    ...FR,
    ...table,
    ...details,
    labels,
    values,
    uncertainty,
    aspects: aspect.aspectNames,
    annexMethod: aspect.annexMethod,
    sectionTitles: { ...FR.sectionTitles, ...(table.sectionTitles ?? {}) },
    lang: language
  };
}

export function sectionTitleFor(code, sectionId) {
  return docStrings(code).sectionTitles[sectionId] ?? sectionId;
}

// ---------------------------------------------------------------------------
// Données visibles (annexe + lecture) et guide d'adaptation culturelle.
// ---------------------------------------------------------------------------

const DETAILS = {
  fr: {
    styleGuide:
      "Écris comme un auteur francophone natif : ton chaleureux, vouvoiement (« vous »), sauf dans les sections qui demandent le tutoiement (la partie transgénérationnelle et la lettre aux figures parentales), phrases fluides et concrètes. Évite les tournures traduites de l'anglais. Adapte les exemples à la culture francophone (rapport à la famille, au travail, à la spiritualité). Vocabulaire astrologique : emploie les termes français consacrés (conjonction, sextile, carré, trigone, opposition).",
    planets: { Sun: "Soleil", Moon: "Lune", Mercury: "Mercure", Venus: "Vénus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturne" },
    signs: {
      Aries: "Bélier", Taurus: "Taureau", Gemini: "Gémeaux", Cancer: "Cancer", Leo: "Lion", Virgo: "Vierge",
      Libra: "Balance", Scorpio: "Scorpion", Sagittarius: "Sagittaire", Capricorn: "Capricorne", Aquarius: "Verseau", Pisces: "Poissons"
    },
    labels: {
      date: "Date de naissance", time: "Heure de naissance", timeInterval: "Heure de naissance (intervalle)",
      place: "Lieu de naissance", tz: "Fuseau horaire", coords: "Coordonnées", zodiac: "Zodiaque",
      houses: "Système de maisons", sect: "Secte du thème", interval: "Analyse d'intervalle", person: "Personne",
      house: "maison", retro: "rétrograde", asc: "Ascendant", mc: "Milieu du Ciel", aspect: "distance angulaire",
      closest: "plus proche candidat", gap: "écart", noOrb: "aucune règle d'orbe active",
      stable: "cible(s) stable(s)", sensitive: "sensible(s)", indeterminate: "indéterminée(s)"
    },
    values: {
      tropical: "tropical", wholeSign: "Whole Sign (maisons entières)", wholeSignShort: "Whole Sign",
      diurnal: "diurne (Soleil au-dessus de l'horizon)", nocturnal: "nocturne (Soleil sous l'horizon)",
      exact: "exacte", approximate: "approximative", unknown: "inconnue"
    },
    uncertainty: {
      unknown: "Heure de naissance inconnue : l'Ascendant, le Milieu du Ciel, les maisons et la secte n'ont pas été calculés.",
      interval: "Heure de naissance fournie en intervalle : aucune heure exacte n'a été inventée."
    }
  },
  en: {
    styleGuide:
      "Write in simple, plain, international English: short sentences, everyday words, no idioms and no unexplained jargon. Many readers are not native English speakers, so keep it easy to read and explain any astrological term in a few words the first time you use it.",
    planets: { Sun: "Sun", Moon: "Moon", Mercury: "Mercury", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
    signs: {
      Aries: "Aries", Taurus: "Taurus", Gemini: "Gemini", Cancer: "Cancer", Leo: "Leo", Virgo: "Virgo",
      Libra: "Libra", Scorpio: "Scorpio", Sagittarius: "Sagittarius", Capricorn: "Capricorn", Aquarius: "Aquarius", Pisces: "Pisces"
    },
    labels: {
      date: "Date of birth", time: "Time of birth", timeInterval: "Time of birth (range)",
      place: "Place of birth", tz: "Time zone", coords: "Coordinates", zodiac: "Zodiac",
      houses: "House system", sect: "Chart sect", interval: "Range analysis", person: "Person",
      house: "house", retro: "retrograde", asc: "Ascendant", mc: "Midheaven", aspect: "angular distance",
      closest: "closest candidate", gap: "gap", noOrb: "no orb rule active",
      stable: "stable target(s)", sensitive: "sensitive", indeterminate: "indeterminate"
    },
    values: {
      tropical: "tropical", wholeSign: "Whole Sign houses", wholeSignShort: "Whole Sign",
      diurnal: "diurnal (Sun above the horizon)", nocturnal: "nocturnal (Sun below the horizon)",
      exact: "exact", approximate: "approximate", unknown: "unknown"
    },
    uncertainty: {
      unknown: "Birth time unknown: the Ascendant, Midheaven, houses and sect were not calculated.",
      interval: "Birth time given as a range: no exact time was invented."
    }
  },
  de: {
    styleGuide:
      "Schreibe wie ein deutschsprachiger Autor: klar, warm und gut gegliedert, mit 'du'. Keine französischen Wendungen. Beispiele an die deutschsprachige Kultur anpassen (Familie, Arbeit, Spiritualität).",
    planets: { Sun: "Sonne", Moon: "Mond", Mercury: "Merkur", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
    signs: {
      Aries: "Widder", Taurus: "Stier", Gemini: "Zwillinge", Cancer: "Krebs", Leo: "Löwe", Virgo: "Jungfrau",
      Libra: "Waage", Scorpio: "Skorpion", Sagittarius: "Schütze", Capricorn: "Steinbock", Aquarius: "Wassermann", Pisces: "Fische"
    },
    labels: {
      date: "Geburtsdatum", time: "Geburtszeit", timeInterval: "Geburtszeit (Zeitspanne)",
      place: "Geburtsort", tz: "Zeitzone", coords: "Koordinaten", zodiac: "Tierkreis",
      houses: "Häusersystem", sect: "Sekt des Horoskops", interval: "Zeitspannen-Analyse", person: "Person",
      house: "Haus", retro: "rückläufig", asc: "Aszendent", mc: "Medium Coeli", aspect: "Winkelabstand",
      closest: "nächster Kandidat", gap: "Abweichung", noOrb: "keine Orbis-Regel aktiv",
      stable: "stabile(s) Ziel(e)", sensitive: "sensibel", indeterminate: "unbestimmt"
    },
    values: {
      tropical: "tropisch", wholeSign: "Ganzzeichen-Häuser", wholeSignShort: "Ganzzeichen",
      diurnal: "Taggeburt (Sonne über dem Horizont)", nocturnal: "Nachtgeburt (Sonne unter dem Horizont)",
      exact: "genau", approximate: "ungefähr", unknown: "unbekannt"
    },
    uncertainty: {
      unknown: "Geburtszeit unbekannt: Aszendent, Medium Coeli, Häuser und Sekt wurden nicht berechnet.",
      interval: "Geburtszeit als Zeitspanne angegeben: es wurde keine genaue Uhrzeit erfunden."
    }
  },
  es: {
    styleGuide:
      "Escribe como un autor hispanohablante nativo: tono cálido, natural y fluido, con 'tú'. Evita calcos del francés. Adapta los ejemplos a la cultura hispanohablante (familia, trabajo, espiritualidad).",
    planets: { Sun: "Sol", Moon: "Luna", Mercury: "Mercurio", Venus: "Venus", Mars: "Marte", Jupiter: "Júpiter", Saturn: "Saturno" },
    signs: {
      Aries: "Aries", Taurus: "Tauro", Gemini: "Géminis", Cancer: "Cáncer", Leo: "Leo", Virgo: "Virgo",
      Libra: "Libra", Scorpio: "Escorpio", Sagittarius: "Sagitario", Capricorn: "Capricornio", Aquarius: "Acuario", Pisces: "Piscis"
    },
    labels: {
      date: "Fecha de nacimiento", time: "Hora de nacimiento", timeInterval: "Hora de nacimiento (intervalo)",
      place: "Lugar de nacimiento", tz: "Zona horaria", coords: "Coordenadas", zodiac: "Zodíaco",
      houses: "Sistema de casas", sect: "Secta de la carta", interval: "Análisis del intervalo", person: "Persona",
      house: "casa", retro: "retrógrado", asc: "Ascendente", mc: "Medio Cielo", aspect: "distancia angular",
      closest: "candidato más cercano", gap: "desviación", noOrb: "ninguna regla de orbe activa",
      stable: "objetivo(s) estable(s)", sensitive: "sensible(s)", indeterminate: "indeterminado(s)"
    },
    values: {
      tropical: "tropical", wholeSign: "casas por signos enteros", wholeSignShort: "signos enteros",
      diurnal: "diurna (Sol sobre el horizonte)", nocturnal: "nocturna (Sol bajo el horizonte)",
      exact: "exacta", approximate: "aproximada", unknown: "desconocida"
    },
    uncertainty: {
      unknown: "Hora de nacimiento desconocida: no se calcularon el Ascendente, el Medio Cielo, las casas ni la secta.",
      interval: "Hora de nacimiento dada como intervalo: no se inventó ninguna hora exacta."
    }
  },
  it: {
    styleGuide:
      "Scrivi come un autore italiano madrelingua: tono caldo, naturale e scorrevole, con 'tu'. Evita calchi dal francese. Adatta gli esempi alla cultura italiana (famiglia, lavoro, spiritualità).",
    planets: { Sun: "Sole", Moon: "Luna", Mercury: "Mercurio", Venus: "Venere", Mars: "Marte", Jupiter: "Giove", Saturn: "Saturno" },
    signs: {
      Aries: "Ariete", Taurus: "Toro", Gemini: "Gemelli", Cancer: "Cancro", Leo: "Leone", Virgo: "Vergine",
      Libra: "Bilancia", Scorpio: "Scorpione", Sagittarius: "Sagittario", Capricorn: "Capricorno", Aquarius: "Acquario", Pisces: "Pesci"
    },
    labels: {
      date: "Data di nascita", time: "Ora di nascita", timeInterval: "Ora di nascita (intervallo)",
      place: "Luogo di nascita", tz: "Fuso orario", coords: "Coordinate", zodiac: "Zodiaco",
      houses: "Sistema delle case", sect: "Setta del tema", interval: "Analisi dell'intervallo", person: "Persona",
      house: "casa", retro: "retrogrado", asc: "Ascendente", mc: "Medio Cielo", aspect: "distanza angolare",
      closest: "candidato più vicino", gap: "scarto", noOrb: "nessuna regola di orbe attiva",
      stable: "obiettivo/i stabile/i", sensitive: "sensibile/i", indeterminate: "indeterminato/i"
    },
    values: {
      tropical: "tropicale", wholeSign: "case a segno intero", wholeSignShort: "segno intero",
      diurnal: "diurna (Sole sopra l'orizzonte)", nocturnal: "notturna (Sole sotto l'orizzonte)",
      exact: "esatta", approximate: "approssimativa", unknown: "sconosciuta"
    },
    uncertainty: {
      unknown: "Ora di nascita sconosciuta: Ascendente, Medio Cielo, case e setta non sono stati calcolati.",
      interval: "Ora di nascita indicata come intervallo: nessuna ora esatta è stata inventata."
    }
  }
};

export function localeDetails(code) {
  return DETAILS[normalizeLanguage(code)] ?? DETAILS.fr;
}

// ---------------------------------------------------------------------------
// Portugais, norvégien (bokmål), danois
// ---------------------------------------------------------------------------

const PT = {
  brand: "Lastro · Leitura simbólica personalizada",
  person: "Pessoa",
  generatedOn: "Gerado em",
  caveat:
    "Enquadramento: esta leitura é um mapa interior, simbólico e não preditivo. Não constitui diagnóstico, nem terapia, nem previsão de acontecimentos. O livre-arbítrio permanece intacto. Os dados astronómicos utilizados são verificados (anexo técnico); as interpretações continuam a ser leituras simbólicas.",
  writerNoteLlm: "Redação: autor IA configurado, secções validadas pela máquina antes da revisão humana.",
  writerNoteTemplate: "Rascunho: autor IA não configurado (sem chave). Este documento não está pronto para entrega.",
  footer:
    "Documento gerado por Lastro — base de cálculo local e determinística; todas as interpretações são etiquetadas e devem ser revistas antes da entrega.",
  badgeCalculated: "Dados verificados (cálculo)",
  badgeSymbolic: "Leitura simbólica",
  badgeUnavailable: "Módulo não disponível nesta versão",
  statusOk: "validado pela máquina",
  statusNeedsReview: "a rever",
  statusNotAvailable: "não disponível",
  statusTemplateDraft: "rascunho (sem autor IA)",
  statusLabelPrefix: "Estado",
  annexShow: "Ver os dados astronómicos utilizados",
  ethicalClosing: "Esta leitura é simbólica: propõe pistas de reflexão, não verdades nem previsões. Continua a ser você o único juiz do que lhe corresponde.",
  annexTitle: "Anexo — base de cálculo verificada",
  annexIntro: "Este anexo contém apenas os dados calculados e verificados desta leitura. Nenhuma interpretação aqui figura.",
  uncertaintyLimits: "Limites de incerteza",
  engineWarnings: "Avisos do motor de cálculo",
  unavailableText:
    "Não é produzida qualquer previsão de acontecimentos: este módulo apresentará janelas amplas, temas de maturação e posturas interiores (0–1 ano, 1–3 anos, 3–5 anos).",
  titlePrefix: "Leitura simbólica",
  sectionTitles: {
    introduction: "O seu céu num relance",
    "position-naissance-axe": "A sua identidade e a sua forma de se exprimir",
    "structure-psychologique": "As suas emoções",
    transgenerationnel: "Leitura transgeracional",
    "archetypes-dominants": "Arquétipos dominantes",
    "grandes-lignes": "As suas grandes linhas",
    "lecture-passe": "O seu passado",
    "lettre-ame": "Carta da alma",
    "lettre-miroir": "Carta espelho",
    "periodes-cycles": "Períodos e ciclos",
    "cles-integration": "Chaves de integração",
    "conclusion-ethique": "Conclusão ética",
    "relations": "As suas relações",
    "action": "A sua maneira de agir",
    "forces-tensions": "As suas forças e tensões"
  }
};

const NO = {
  brand: "Lastro · Personlig symbolsk lesning",
  person: "Person",
  generatedOn: "Generert",
  caveat:
    "Ramme: denne lesningen er et indre, symbolsk og ikke-forutsigende kart. Den er verken diagnose, terapi eller forutsigelse av hendelser. Den frie viljen er intakt. De astronomiske dataene som brukes er verifisert (teknisk vedlegg); tolkningene er symbolske.",
  writerNoteLlm: "Tekst: AI-forfatter konfigurert, avsnitt maskinvalidert før menneskelig gjennomgang.",
  writerNoteTemplate: "Utkast: AI-forfatter ikke konfigurert (ingen nøkkel). Dokumentet er ikke klart for levering.",
  footer:
    "Dokument generert av Lastro — lokalt og deterministisk beregningsgrunnlag; hver tolkning er merket og må gjennomgås før levering.",
  badgeCalculated: "Verifiserte data (beregning)",
  badgeSymbolic: "Symbolsk lesning",
  badgeUnavailable: "Modulen er ikke tilgjengelig i denne versjonen",
  statusOk: "maskinvalidert",
  statusNeedsReview: "til gjennomgang",
  statusNotAvailable: "ikke tilgjengelig",
  statusTemplateDraft: "utkast (uten AI-forfatter)",
  statusLabelPrefix: "Status",
  annexShow: "Se de astronomiske dataene som er brukt",
  ethicalClosing: "Denne lesningen er symbolsk: den gir refleksjonspunkter, ikke sannheter eller forutsigelser. Du er selv den eneste dommeren over hva som passer deg.",
  annexTitle: "Vedlegg — verifisert beregningsgrunnlag",
  annexIntro: "Dette vedlegget inneholder bare de beregnede og verifiserte dataene for denne lesningen. Ingen tolkning står her.",
  uncertaintyLimits: "Usikkerhetsgrenser",
  engineWarnings: "Varsler fra beregningsmotoren",
  unavailableText:
    "Det gis ingen forutsigelse av hendelser: denne modulen vil gi brede tidsvinduer, modningstemaer og indre holdninger (0–1 år, 1–3 år, 3–5 år).",
  titlePrefix: "Symbolsk lesning",
  sectionTitles: {
    introduction: "Himmelen din i korte trekk",
    "position-naissance-axe": "Identiteten din og måten du uttrykker deg på",
    "structure-psychologique": "Følelsene dine",
    transgenerationnel: "Transgenerasjonell lesning",
    "archetypes-dominants": "Dominerende arketyper",
    "grandes-lignes": "Dine store linjer",
    "lecture-passe": "Fortiden din",
    "lettre-ame": "Sjelebrev",
    "lettre-miroir": "Speilbrev",
    "periodes-cycles": "Perioder og sykluser",
    "cles-integration": "Nøkler til integrasjon",
    "conclusion-ethique": "Etisk avslutning",
    "relations": "Relasjonene dine",
    "action": "Måten du handler på",
    "forces-tensions": "Dine styrker og spenninger"
  }
};

const DA = {
  brand: "Lastro · Personlig symbolsk læsning",
  person: "Person",
  generatedOn: "Genereret",
  caveat:
    "Ramme: denne læsning er et indre, symbolsk og ikke-forudsigende kort. Den er hverken diagnose, terapi eller forudsigelse af begivenheder. Den frie vilje er intakt. De anvendte astronomiske data er verificeret (teknisk bilag); fortolkningerne er symbolske.",
  writerNoteLlm: "Tekst: AI-forfatter konfigureret, afsnit maskinvalideret før menneskelig gennemlæsning.",
  writerNoteTemplate: "Kladde: AI-forfatter ikke konfigureret (ingen nøgle). Dokumentet er ikke klar til levering.",
  footer:
    "Dokument genereret af Lastro — lokalt og deterministisk beregningsgrundlag; hver fortolkning er mærket og skal gennemgås før levering.",
  badgeCalculated: "Verificerede data (beregning)",
  badgeSymbolic: "Symbolsk læsning",
  badgeUnavailable: "Modulet er ikke tilgængeligt i denne version",
  statusOk: "maskinvalideret",
  statusNeedsReview: "til gennemgang",
  statusNotAvailable: "ikke tilgængelig",
  statusTemplateDraft: "kladde (uden AI-forfatter)",
  statusLabelPrefix: "Status",
  annexShow: "Se de anvendte astronomiske data",
  ethicalClosing: "Denne læsning er symbolsk: den giver refleksionspunkter, ikke sandheder eller forudsigelser. Du er selv den eneste dommer over, hvad der passer til dig.",
  annexTitle: "Bilag — verificeret beregningsgrundlag",
  annexIntro: "Dette bilag indeholder kun de beregnede og verificerede data for denne læsning. Der står ingen fortolkning her.",
  uncertaintyLimits: "Usikkerhedsgrænser",
  engineWarnings: "Advarsler fra beregningsmotoren",
  unavailableText:
    "Der gives ingen forudsigelse af begivenheder: dette modul vil give brede tidsvinduer, modningstemaer og indre holdninger (0–1 år, 1–3 år, 3–5 år).",
  titlePrefix: "Symbolsk læsning",
  sectionTitles: {
    introduction: "Din himmel i korte træk",
    "position-naissance-axe": "Din identitet og måden du udtrykker dig på",
    "structure-psychologique": "Dine følelser",
    transgenerationnel: "Transgenerationel læsning",
    "archetypes-dominants": "Dominerende arketyper",
    "grandes-lignes": "Dine store linjer",
    "lecture-passe": "Din fortid",
    "lettre-ame": "Sjælebrev",
    "lettre-miroir": "Spejlbrev",
    "periodes-cycles": "Perioder og cyklusser",
    "cles-integration": "Nøgler til integration",
    "conclusion-ethique": "Etisk afslutning",
    "relations": "Dine relationer",
    "action": "Måden du handler på",
    "forces-tensions": "Dine styrker og spændinger"
  }
};

DOCS.pt = PT;
DOCS.no = NO;
DOCS.da = DA;

DETAILS.pt = {
  styleGuide:
    "Escreve como um autor português nativo: tom caloroso, natural e fluido, tratando por 'tu'. Evita decalques do francês. Adapta os exemplos à cultura portuguesa (família, trabalho, espiritualidade).",
  planets: { Sun: "Sol", Moon: "Lua", Mercury: "Mercúrio", Venus: "Vénus", Mars: "Marte", Jupiter: "Júpiter", Saturn: "Saturno" },
  signs: {
    Aries: "Carneiro", Taurus: "Touro", Gemini: "Gémeos", Cancer: "Caranguejo", Leo: "Leão", Virgo: "Virgem",
    Libra: "Balança", Scorpio: "Escorpião", Sagittarius: "Sagitário", Capricorn: "Capricórnio", Aquarius: "Aquário", Pisces: "Peixes"
  },
  labels: {
    date: "Data de nascimento", time: "Hora de nascimento", timeInterval: "Hora de nascimento (intervalo)",
    place: "Local de nascimento", tz: "Fuso horário", coords: "Coordenadas", zodiac: "Zodíaco",
    houses: "Sistema de casas", sect: "Secta do tema", interval: "Análise do intervalo", person: "Pessoa",
    house: "casa", retro: "retrógrado", asc: "Ascendente", mc: "Meio do Céu", aspect: "distância angular",
    closest: "candidato mais próximo", gap: "desvio", noOrb: "nenhuma regra de orbe ativa",
    stable: "objetivo(s) estável(is)", sensitive: "sensível(is)", indeterminate: "indeterminado(s)"
  },
  values: {
    tropical: "tropical", wholeSign: "casas por signos inteiros", wholeSignShort: "signos inteiros",
    diurnal: "diurna (Sol acima do horizonte)", nocturnal: "noturna (Sol abaixo do horizonte)",
    exact: "exata", approximate: "aproximada", unknown: "desconhecida"
  },
  uncertainty: {
    unknown: "Hora de nascimento desconhecida: o Ascendente, o Meio do Céu, as casas e a secta não foram calculados.",
    interval: "Hora de nascimento indicada como intervalo: nenhuma hora exata foi inventada."
  }
};

DETAILS.no = {
  styleGuide:
    "Skriv som en norsk forfatter: varm, naturlig og flytende, med 'du'. Unngå franske vendinger. Tilpass eksemplene til norsk kultur (familie, arbeid, åndelighet).",
  planets: { Sun: "Solen", Moon: "Månen", Mercury: "Merkur", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
  signs: {
    Aries: "Væren", Taurus: "Tyren", Gemini: "Tvillingene", Cancer: "Krepsen", Leo: "Løven", Virgo: "Jomfruen",
    Libra: "Vekten", Scorpio: "Skorpionen", Sagittarius: "Skytten", Capricorn: "Steinbukken", Aquarius: "Vannmannen", Pisces: "Fiskene"
  },
  labels: {
    date: "Fødselsdato", time: "Fødselstid", timeInterval: "Fødselstid (intervall)",
    place: "Fødested", tz: "Tidssone", coords: "Koordinater", zodiac: "Dyrekrets",
    houses: "Hussystem", sect: "Sekt", interval: "Intervallanalyse", person: "Person",
    house: "hus", retro: "retrograd", asc: "Ascendant", mc: "Medium Coeli", aspect: "vinkelavstand",
    closest: "nærmeste kandidat", gap: "avvik", noOrb: "ingen orbis-regel aktiv",
    stable: "stabilt mål", sensitive: "sensitiv", indeterminate: "ubestemt"
  },
  values: {
    tropical: "tropisk", wholeSign: "heltegnshus", wholeSignShort: "heltegn",
    diurnal: "dag (Solen over horisonten)", nocturnal: "natt (Solen under horisonten)",
    exact: "nøyaktig", approximate: "omtrentlig", unknown: "ukjent"
  },
  uncertainty: {
    unknown: "Fødselstid ukjent: Ascendant, Medium Coeli, hus og sekt er ikke beregnet.",
    interval: "Fødselstid oppgitt som intervall: ingen eksakt tid er oppfunnet."
  }
};

DETAILS.da = {
  styleGuide:
    "Skriv som en dansk forfatter: varm, naturlig og flydende, med 'du'. Undgå franske vendinger. Tilpas eksemplerne til dansk kultur (familie, arbejde, spiritualitet).",
  planets: { Sun: "Solen", Moon: "Månen", Mercury: "Merkur", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturn" },
  signs: {
    Aries: "Vædderen", Taurus: "Tyren", Gemini: "Tvillingerne", Cancer: "Krebsen", Leo: "Løven", Virgo: "Jomfruen",
    Libra: "Vægten", Scorpio: "Skorpionen", Sagittarius: "Skytten", Capricorn: "Stenbukken", Aquarius: "Vandmanden", Pisces: "Fiskene"
  },
  labels: {
    date: "Fødselsdato", time: "Fødselstidspunkt", timeInterval: "Fødselstidspunkt (interval)",
    place: "Fødested", tz: "Tidszone", coords: "Koordinater", zodiac: "Zodiak",
    houses: "Hussystem", sect: "Sekt", interval: "Intervalanalyse", person: "Person",
    house: "hus", retro: "retrograd", asc: "Ascendant", mc: "Medium Coeli", aspect: "vinkelafstand",
    closest: "nærmeste kandidat", gap: "afvigelse", noOrb: "ingen orbis-regel aktiv",
    stable: "stabilt mål", sensitive: "sensitiv", indeterminate: "ubestemt"
  },
  values: {
    tropical: "tropisk", wholeSign: "heltegnshuse", wholeSignShort: "heltegn",
    diurnal: "dag (Solen over horisonten)", nocturnal: "nat (Solen under horisonten)",
    exact: "præcis", approximate: "omtrentlig", unknown: "ukendt"
  },
  uncertainty: {
    unknown: "Fødselstidspunkt ukendt: Ascendant, Medium Coeli, huse og sekt er ikke beregnet.",
    interval: "Fødselstidspunkt angivet som interval: ingen præcis tid er opfundet."
  }
};

// ---------------------------------------------------------------------------
// Néerlandais
// ---------------------------------------------------------------------------

const NL = {
  brand: "Lastro · Persoonlijke symbolische lezing",
  person: "Persoon",
  generatedOn: "Gegenereerd op",
  caveat:
    "Kader: deze lezing is een innerlijke, symbolische en niet-voorspellende kaart. Ze is geen diagnose, geen therapie en geen voorspelling van gebeurtenissen. De vrije wil blijft volledig intact. De gebruikte astronomische gegevens zijn geverifieerd (technische bijlage); de interpretaties blijven symbolisch.",
  writerNoteLlm: "Tekst: AI-auteur geconfigureerd, secties machinaal gevalideerd vóór menselijke controle.",
  writerNoteTemplate: "Concept: AI-auteur niet geconfigureerd (geen sleutel). Dit document is niet klaar voor levering.",
  footer:
    "Document gegenereerd door Lastro — lokale en deterministische rekenbasis; elke interpretatie is gelabeld en moet vóór levering worden nagekeken.",
  badgeCalculated: "Geverifieerde gegevens (berekening)",
  badgeSymbolic: "Symbolische lezing",
  badgeUnavailable: "Module niet beschikbaar in deze versie",
  statusOk: "machinaal gevalideerd",
  statusNeedsReview: "na te kijken",
  statusNotAvailable: "niet beschikbaar",
  statusTemplateDraft: "concept (zonder AI-auteur)",
  statusLabelPrefix: "Status",
  annexShow: "Bekijk de gebruikte astronomische gegevens",
  ethicalClosing: "Deze lezing is symbolisch: ze biedt reflectiepunten, geen waarheden of voorspellingen. Jij blijft de enige rechter over wat bij je past.",
  annexTitle: "Bijlage — geverifieerde rekenbasis",
  annexIntro: "Deze bijlage bevat alleen de berekende en geverifieerde gegevens van deze lezing. Er staat geen interpretatie in.",
  uncertaintyLimits: "Onzekerheidsgrenzen",
  engineWarnings: "Waarschuwingen van de rekenmodule",
  unavailableText:
    "Er worden geen gebeurtenissen voorspeld: deze module geeft brede tijdvensters, rijpingsthema's en innerlijke houdingen (0–1 jaar, 1–3 jaar, 3–5 jaar).",
  titlePrefix: "Symbolische lezing",
  sectionTitles: {
    introduction: "Je hemel in één oogopslag",
    "position-naissance-axe": "Je identiteit en hoe je je uitdrukt",
    "structure-psychologique": "Je emoties",
    transgenerationnel: "Transgenerationele lezing",
    "archetypes-dominants": "Dominante archetypen",
    "grandes-lignes": "Je grote lijnen",
    "lecture-passe": "Je verleden",
    "lettre-ame": "Zielsbrief",
    "lettre-miroir": "Spiegelbrief",
    "periodes-cycles": "Periodes en cycli",
    "cles-integration": "Sleutels tot integratie",
    "conclusion-ethique": "Ethische afsluiting",
    "relations": "Je relaties",
    "action": "Hoe je handelt",
    "forces-tensions": "Je krachten en spanningen"
  }
};

DOCS.nl = NL;

DETAILS.nl = {
  styleGuide:
    "Schrijf als een Nederlandse auteur: warm, natuurlijk en vlot, met 'je'. Vermijd Franse wendingen. Pas de voorbeelden aan de Nederlandse cultuur aan (gezin, werk, spiritualiteit).",
  planets: { Sun: "Zon", Moon: "Maan", Mercury: "Mercurius", Venus: "Venus", Mars: "Mars", Jupiter: "Jupiter", Saturn: "Saturnus" },
  signs: {
    Aries: "Ram", Taurus: "Stier", Gemini: "Tweelingen", Cancer: "Kreeft", Leo: "Leeuw", Virgo: "Maagd",
    Libra: "Weegschaal", Scorpio: "Schorpioen", Sagittarius: "Boogschutter", Capricorn: "Steenbok", Aquarius: "Waterman", Pisces: "Vissen"
  },
  labels: {
    date: "Geboortedatum", time: "Geboortetijd", timeInterval: "Geboortetijd (interval)",
    place: "Geboorteplaats", tz: "Tijdzone", coords: "Coördinaten", zodiac: "Dierenriem",
    houses: "Huizensysteem", sect: "Secte van de kaart", interval: "Intervalanalyse", person: "Persoon",
    house: "huis", retro: "retrograde", asc: "Ascendant", mc: "Medium Coeli", aspect: "hoekafstand",
    closest: "dichtstbijzijnde kandidaat", gap: "afwijking", noOrb: "geen orbis-regel actief",
    stable: "stabiel doel", sensitive: "gevoelig", indeterminate: "onbepaald"
  },
  values: {
    tropical: "tropisch", wholeSign: "hele-tekenhuizen", wholeSignShort: "hele teken",
    diurnal: "dag (Zon boven de horizon)", nocturnal: "nacht (Zon onder de horizon)",
    exact: "exact", approximate: "bij benadering", unknown: "onbekend"
  },
  uncertainty: {
    unknown: "Geboortetijd onbekend: Ascendant, Medium Coeli, huizen en secte zijn niet berekend.",
    interval: "Geboortetijd als interval opgegeven: er is geen exacte tijd verzonnen."
  }
};

// ---------------------------------------------------------------------------
// Mention de relecture automatique (affichée dans le document)
// ---------------------------------------------------------------------------

const AI_REVIEW_NOTES = {
  fr: "Texte rédigé par une IA — {n} relectures et corrections automatiques — non relu par un humain.",
  en: "Text written by an AI — {n} automatic reviews and corrections — not reviewed by a human.",
  de: "Text von einer KI verfasst — {n} automatische Prüfungen und Korrekturen — nicht von einem Menschen geprüft.",
  es: "Texto redactado por una IA — {n} revisiones y correcciones automáticas — no revisado por un humano.",
  it: "Testo scritto da un'IA — {n} revisioni e correzioni automatiche — non rivisto da un essere umano.",
  pt: "Texto redigido por uma IA — {n} revisões e correções automáticas — não revisto por um humano.",
  no: "Tekst skrevet av en KI — {n} automatiske gjennomganger og korreksjoner — ikke gjennomgått av et menneske.",
  da: "Tekst skrevet af en AI — {n} automatiske gennemgange og rettelser — ikke gennemgået af et menneske.",
  nl: "Tekst geschreven door een AI — {n} automatische controles en correcties — niet nagekeken door een mens."
};

export function aiReviewNote(code, passes, humanReviewed = false) {
  const language = normalizeLanguage(code);
  if (humanReviewed) {
    const human = {
      fr: "Cette lecture a été relue et validée par un praticien.",
      en: "This reading has been reviewed and approved by a practitioner.",
      de: "Diese Deutung wurde von einem Praktiker geprüft und freigegeben.",
      es: "Esta lectura ha sido revisada y validada por un profesional.",
      it: "Questa lettura è stata rivista e validata da un professionista.",
      pt: "Esta leitura foi revista e validada por um profissional.",
      no: "Denne lesningen er gjennomgått og godkjent av en utøver.",
      da: "Denne læsning er gennemgået og godkendt af en udøver.",
      nl: "Deze lezing is nagekeken en goedgekeurd door een beoefenaar."
    };
    return human[language] ?? human.fr;
  }
  const template = AI_REVIEW_NOTES[language] ?? AI_REVIEW_NOTES.fr;
  return template.replace("{n}", String(passes));
}
