// Daily horoscope for a sign — small, soft, non-deterministic text.
// Generated by the configured LLM when available, otherwise a neutral template.
// Public (no account), no data stored.

import { FR_SIGNS } from "../deliverables/french.mjs";
import { callChatCompletions, llmConfiguration } from "../deliverables/writers.mjs";

const SIGN_KEYS = Object.freeze({
  aries: { fr: "Bélier", glyph: "♈" },
  taurus: { fr: "Taureau", glyph: "♉" },
  gemini: { fr: "Gémeaux", glyph: "♊" },
  cancer: { fr: "Cancer", glyph: "♋" },
  leo: { fr: "Lion", glyph: "♌" },
  virgo: { fr: "Vierge", glyph: "♍" },
  libra: { fr: "Balance", glyph: "♎" },
  scorpio: { fr: "Scorpion", glyph: "♏" },
  sagittarius: { fr: "Sagittaire", glyph: "♐" },
  capricorn: { fr: "Capricorne", glyph: "♑" },
  aquarius: { fr: "Verseau", glyph: "♒" },
  pisces: { fr: "Poissons", glyph: "♓" }
});

const FR_TO_KEY = Object.freeze(
  Object.fromEntries(Object.entries(SIGN_KEYS).map(([key, value]) => [key, value.fr.toLowerCase()]))
);

function normalizeName(value) {
  return String(value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\s'’]+/g, "");
}

export function resolveSignKey(input) {
  const value = normalizeName(input);
  if (SIGN_KEYS[value]) {
    return value;
  }
  const entry = Object.entries(SIGN_KEYS).find(([, meta]) => normalizeName(meta.fr) === value);
  return entry ? entry[0] : null;
}

function parseJsonObject(text) {
  const cleaned = String(text)
    .replace(/```(?:json)?/gi, "")
    .trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    return null;
  }
  try {
    return JSON.parse(cleaned.slice(start, end + 1));
  } catch {
    return null;
  }
}

function templateHoroscope(signMeta) {
  return {
    amour: "Les échanges se font en douceur ; laissez la place à l'écoute.",
    travail: "Une journée pour avancer à votre rythme, sans forcer.",
    bienEtre: "Accordez-vous une vraie pause, même brève."
  };
}

function frenchDate() {
  return new Intl.DateTimeFormat("fr-FR", { weekday: "long", day: "numeric", month: "long" }).format(new Date());
}

export async function generateDailyHoroscope(input, options = {}) {
  const key = resolveSignKey(input);
  if (!key) {
    const error = new Error("Signe inconnu. Utilisez un signe du zodiaque (ex. bélier).");
    error.status = 400;
    throw error;
  }
  const meta = SIGN_KEYS[key];
  const sign = { key, fr: meta.fr, glyph: meta.glyph };
  let provider = "template";

  const configured = options.config ?? llmConfiguration();
  if (configured) {
    try {
      const result = await callChatCompletions(configured, {
        system:
          "Tu écris des horoscopes du jour courts, doux, non déterministes, sans prédiction d'événement ni de date.",
        user:
          `Pour le signe ${meta.fr} (${meta.glyph}), rédige l'horoscope du jour en français, 3 mini-sections : ` +
          `"Amour", "Travail", "Bien-être", chacune en 1 à 2 phrases, ton positif et inspirant. ` +
          `Réponds UNIQUEMENT en JSON avec exactement les clés amour, travail, bienEtre (sans texte autour).`,
        temperature: 0.8
      });
      const parsed = parseJsonObject(result.text);
      if (parsed) {
        return {
          sign,
          day: frenchDate(),
          horoscope: {
            amour: String(parsed.amour ?? "").trim() || null,
            travail: String(parsed.travail ?? "").trim() || null,
            bienEtre: String(parsed.bienEtre ?? "").trim() || null
          },
          provider: "llm",
          generatedAt: new Date().toISOString()
        };
      }
    } catch {
      // fallback à la version neutre
    }
  }

  return {
    sign,
    day: frenchDate(),
    horoscope: templateHoroscope(),
    provider,
    generatedAt: new Date().toISOString()
  };
}

export function signGlyphForEntry(entry) {
  return FR_SIGNS.find((candidate) => candidate.fr === entry?.fr)?.symbol ?? entry?.glyph ?? null;
}
